### PR TITLE
Add Wi-Fi support

### PR DESCRIPTION
**Pull request by ivq**
The PR is a little big. But I tried to keep all commits simple and straightforward.

### CODE REVIEW

**Comment by Pavlos1** [comment]
Hi. Not a maintainer, but: do I need to flash [this M0 firmware](https://github.com/bouffalolab/bl_iot_sdk/tree/master/customer_app/bl808/bl808_demo_linux) for this PR to work?

**Comment by ivq** [comment]
> Hi. Not a maintainer, but: do I need to flash [this M0 firmware](https://github.com/bouffalolab/bl_iot_sdk/tree/master/customer_app/bl808/bl808_demo_linux?rgh-link-date=2023-11-25T09%3A32%3A43Z) for this PR to work?

No. The PR would do everything for you. It adds package blwnet_xram and the M0 firmware in binary form is provided by the package so bl_iot_sdk is not needed. The firmware only needs to reside in /lib/firmware in the rootfs.

**Comment by Pavlos1** [comment]
Oh cool there's even [wifi debug information](https://github.com/openbouffalo/buildroot_bouffalo/files/13464204/ox64_wifi_redacted.txt) on the other (M0) UART.

I wonder why it's not picking up any of my SSIDs then. It's setting the region to China but it [seems](https://en.wikipedia.org/wiki/List_of_WLAN_channels#2.4_GHz_(IEEE_802.11b-1999|802.11b/IEEE_802.11g-2003|g/IEEE_802.11n-2009|n/Wi-Fi_6|ax)) that the channels should be more or less compatible with the Australian ones.

Also since this replaces the existing M0 firmware at runtime, it no longer runs the Mailbox / IRQ Forwarding thing. I'm curious what the consequences of this are for the rest of the system.

**Comment by ivq** [comment]
> Oh cool there's even [wifi debug information](https://github.com/openbouffalo/buildroot_bouffalo/files/13464204/ox64_wifi_redacted.txt) on the other (M0) UART.
> 
> I wonder why it's not picking up any of my SSIDs then. It's setting the region to China but it [seems](https://en.wikipedia.org/wiki/List_of_WLAN_channels#2.4_GHz_(IEEE_802.11b-1999%7C802.11b/IEEE_802.11g-2003%7Cg/IEEE_802.11n-2009%7Cn/Wi-Fi_6%7Cax)) that the channels should be more or less compatible with the Australian ones.
The root cause should be that your router enabled MFP/WPA3 and the firmware is not compatible. This issue have been fixed. See https://github.com/openbouffalo/buildroot_bouffalo/pull/82.
> Also since this replaces the existing M0 firmware at runtime, it no longer runs the Mailbox / IRQ Forwarding thing. I'm curious what the consequences of this are for the rest of the system.

D0 is using IRQ chip driver, so it no more depends on M0 forwarding IRQ.

**Comment by Pavlos1** [comment]
Before #82 was merged I did get it to connect to pinephone's hotspot, so I can confirm that the issue is specific to my router.

However, even with the latest version of `blwnet_xram` it still won't connect or even find my [router](https://www.asus.com/au/networking-iot-servers/wifi-routers/asus-gaming-routers/tuf-gaming-ax3000/)'s SSID during the scan. And the router is explicitly configured to use WPA2.

Using a different wireless connection isn't a big issue for me, but if you would like any more information for the purposes of making these chips work with a wider set of routers then let me know.

Update: it was purely a range issue. The chip antenna on the Ox64 isn't very good..

**Pull request merged**
